### ISSUE TITLE
iOS Pods folder/files are not generated/present

### ISSUE THREAD

**Issue by margce** [WurthElektronik/Proteus-Connect#2]
Hi, I'm new to developing app for iOS but not to firmware development. When trying to setup this new app version I can clone the latest repo, followed the instructions to install all dependancies but after generating the xcode target files with 
_ionic cap build ios --prod_ 

Project launches but it fails to compile because all the files pointing to Pods directory are not there nor is the Pods.xcworkspace file. Can you please tell me what i'm missing?

Thanks
Martin

**Comment by margce** [comment]
Seems like installing cocoa-pods was a prerequisite that is not listed. I installed via _brew install cocoapds_ and after re running the ionic cap build ios command all dependencies were generated.

**Comment by wm-eisos** [comment]
thanks for letting us know will update the read me file.
i will keep this issue open to track.

**Comment by wm-eisos** [comment]
This issue will be closed since the readme was updated
