### ISSUE TITLE
Inconsistent connection setup in case of peripheral not supporting the requested UUIDs

### ISSUE THREAD

**Issue by mah-eiSmart** [WurthElektronik/Proteus-Connect#4]
In case the peripheral does not support the UUIDs of the SPP-like profile, the app still sets up the connection and tries to use the non-existent UUIDs.
The right behavior would be:
-check if the UUIDs really exist
-if they do not exist, shit down connection

**Comment by wm-eisos** [comment]
Fixed in release 1.7 1b70f0fa68c7f99a2db9febabe7417e2097ecd6d
